version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: unyleya-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ~/banco-de-dados/unyleya-mongodb:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
          