version: '3'

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: unyleya-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ~/banco-de-dados/unyleya-mongodb:/data/db
